---
title: "Lab5, Luxembourg maps"
author: "Lidya Tedros"
date: "dx27459@umbc.edu"
output: html_document
---

```{r setup, include=FALSE}
library(tidycensus)
library(tidyverse)
library(tigris)
library(Rcpp)
library(terra)
library(maptiles)
library(remotes)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## terra 1.7.19
p <- vect(system.file("ex/lux.shp", package="terra"))
```
 
```{r}
plot(p)
```

```{r}
n <- nrow(p)
plot(p, col=rainbow(n))
```

```{r}
plot(p, "NAME_2", col=rainbow(25))
```

```{r}
plot(p, c("NAME_1", "NAME_2"), col=rainbow(25))
```

```{r}
par(mfrow=c(1,2))
m <- c(3.1, 3.1, 2.1, 2.1)
plot(p, "NAME_1", col=rainbow(25), mar=m, plg=list(x="topright"), pax=list(las=1))
plot(p, "NAME_2", col=rainbow(25), mar=m, plg=list(x="topright", cex=.75), pax=list(las=1))
```

```{r}
par(mfrow=c(1,2))
m <- c(3.1, 3.1, 1.1, 1.1)
plot(p, "NAME_1", col=rainbow(25), mar=m, plg=list(x="topright", title="District", bty = "o"), main="", axes=FALSE)
axis(1, at=c(5,7)); axis(1)
axis(2, at=c(49,51)); axis(2, las=1)
plot(p, "NAME_2", col=rainbow(25), mar=m, plg=list(x="topright", cex=.75, title="Canton", bty = "o"), main="", axes=FALSE)
axis(1, at=c(5, 7)); axis(1)
```

```{r}
d <- aggregate(p, "NAME_1")
plot(p, col="light blue", lty=2, border="red", lwd=2)
lines(d, lwd=5)
lines(d, col="white", lwd=1)
text(p, "NAME_2", cex=.8, halo=TRUE)
```

```{r}
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
```

```{r}
plot(r)
```

```{r}
plot(r)
lines(p, lwd=2)
set.seed(12)
xy <- spatSample(r, 20, "random", na.rm=TRUE, xy=TRUE)
points(xy, pch=20, col="red", cex=2)
```

```{r}
m <- c(3.1, 3.1, 1.1, 1.1)
plot(r, type="interval", plg=list(x="topright"), mar=m)
```

```{r}
rr <- round(r/100)
plot(rr, plg=list(x="topright"), mar=m)
```

```{r}
x <- classify(r, c(140, 300, 400, 550))
levels(x) <- data.frame(id=0:2, elevation=c("low", "intermediate", "high"))
is.factor(x)
## [1] TRUE
x
## class       : SpatRaster
## dimensions  : 90, 95, 1  (nrow, ncol, nlyr)
## resolution  : 0.008333333, 0.008333333  (x, y)
## extent      : 5.741667, 6.533333, 49.44167, 50.19167  (xmin, xmax, ymin, ymax)
## coord. ref. : lon/lat WGS 84 (EPSG:4326)
## source(s)   : memory
## categories  : elevation
## name        : elevation
## min value   :       low
## max value   :      high
plot(x, col=c("green", "blue", "light gray"))
```

```{r}
b <- rast(system.file("ex/logo.tif", package="terra"))
plot(b)
```

```{r}
r <- rast(p, res=0.01 )
values(r) <- 1:ncell(r)
r <- mask(r, p)
```

```{r}
plotRGB(b, r=1, g=2, b=3)
```

```{r}
f <- system.file("ex/lux.shp", package="terra")
p <- vect(f)
```

```{r}
bg <- get_tiles(ext(p))
plotRGB(bg)
lines(p, col="blue", lwd=3)
```


```{r}
devtools::install_github("rstudio/leaflet")
```


```{r}
m <- plet(p)
m

```

